### ISSUE TITLE
Embedded SQL image does not successfully deploy

### ISSUE THREAD

**Issue by RajatNair** [chrisns/scrumonline#3]
Hi,

Tried deploying the embedded SQL image with volume mounting based on instructions in `readme` but it fails with file not found error. 
`docker run -d --name scrumonline -p 8080:80 -e HOST="http://localhost:8080" -v ${PWD}/db:/var/lib/mysql chrisns/scrumonline:bundled /mysql_init.sh`

Based on https://github.com/chrisns/scrumonline/blob/master/Dockerfile#L10 the file is copied inside `scrumonline` folder. So tried this -
`docker run -d --name scrumonline -p 8080:80 -e HOST="http://localhost:8080" -v ${PWD}/db:/var/lib/mysql chrisns/scrumonline:bundled   /scrumonline/mysql_init.sh` 
This time it ran successfully but UI does not come up. Docker logs says it's waiting for mysql instance. That message in printed repeatedly. 

Any idea on issue here?

**Comment by chrisns** [comment]
Hi
sorry there was a critical `.` missing in the readme, fixed here https://github.com/chrisns/scrumonline/commit/d57696ee515c1f546de0ec8f5755a555a7f36a6c#diff-04c6e90faac2675aa89e2176d2eec7d8R40
for me running it:
```bash
$ docker run --rm -ti -v ${PWD}/db:/var/lib/mysql chrisns/scrumonline:bundled ./mysql_init.sh
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
ATTENTION: This operation should not be executed in a production environment.

Creating database schema...
Database schema created successfully!
Processing entity "Member"
Processing entity "Poll"
Processing entity "Session"
Processing entity "Vote"

Proxy classes generated to "/scrumonline/src/proxies"
```
that creates the db, then you can start it with:

```bash
$ docker run -d --name scrumonline -p 8080:80 -e HOST="http://localhost:8080" -v ${PWD}/db:/var/lib/mysql chrisns/scrumonline:bundled
```

does that help?
you might have to wait a while for it to start if you're on a slower machine maybe

**Comment by RajatNair** [comment]
Appreciate the quick response 👍 

Running `$ docker run --rm -ti -v ${PWD}/db:/var/lib/mysql chrisns/scrumonline:bundled ./mysql_init.sh` on an VM with 8 cores and 16 gigs of RAM. 60 minutes later, I still see `=> Waiting for confirmation of MySQL service startup` in the console. Could something have gone wrong? Would it take this long?

**Comment by chrisns** [comment]
Hey. Yeah. Shouldn’t take more than a few seconds.
Maybe permissions? You can docker exec on while it’s running and see the MySQL logs

**Comment by RajatNair** [comment]
Any specific location? Logs at `/var/log/mysql/error.log` is empty.

Running command again as root. Still seeing `Waiting for confirmation of MySQL service startup` in console.

![image](https://user-images.githubusercontent.com/3319907/80748555-b9d3f680-8b42-11ea-85f0-dd70de0d0685.png)

**Comment by RajatNair** [comment]
So checked `mysql_init.sh` script and tried running the command `mysql -uroot -e "status"` and this is the output -

>ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by RajatNair** [comment]
I managed to get this to work. Just not sure which command fixed it though. 

I connected to running container using `docker exec`. 
1. I created `mysqld.sock` file -
`touch /var/run/mysqld/mysqld.sock`
2. Gave `mysql` user and group permission to following directories -
`chown -R mysql:mysql /var/lib/mysql /var/run/mysqld`

It kicked me out of `docker exec` session and I could see this - 
![image](https://user-images.githubusercontent.com/3319907/80750578-f6552180-8b45-11ea-8a4e-301275c373d2.png)

After 3.5 hours - it finally worked! 😃
